name: Build and Publish Package

on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      env:
        NODE_VERSION: 16.x

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      env:
        NODE_VERSION: 16.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine
    - name: Get tag name
      run: |
        echo "Tag name: ${GITHUB_REF#refs/tags/}"

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo "Publishing package to pypi"
        # twine upload dist/*
        # echo "Publishing package to GitHub"
        # twine upload --verbose --repository-url https://upload.github.com \
        #  -u ${{ github.actor }} -p ${{ secrets.RELEASE_TOKEN }} \
        #  dist/*
